//! Generates `SQL_KEYWORDS` from the table `libinjection` keeps in
//! `data/sqli_keywords.txt`, so that the two crates share one copy of it.

use std::{env, fs, path::Path};

/// The data file of the sibling crate: `KEY<TAB>BYTE` rows, sorted by key.
const DATA: &str = "../libinjection-rs/data/sqli_keywords.txt";

/// The `TokenType` a table value stands for.
fn token_type(byte: &str) -> &'static str {
    match byte {
        "k" => "Keyword",
        "U" => "Union",
        "B" => "Group",
        "E" => "Expression",
        "t" => "SqlType",
        "f" => "Function",
        "n" => "Bareword",
        "1" => "Number",
        "v" => "Variable",
        "s" => "String",
        "o" => "Operator",
        "&" => "LogicOperator",
        "c" => "Comment",
        "A" => "Collate",
        "T" => "Tsql",
        "F" => "Fingerprint",
        _ => panic!("unknown keyword type {byte:?}"),
    }
}

fn main() {
    let data = Path::new(env!("CARGO_MANIFEST_DIR")).join(DATA);
    println!("cargo:rerun-if-changed={}", data.display());
    let text = fs::read_to_string(&data).unwrap_or_else(|e| panic!("{}: {e}", data.display()));

    let rows: Vec<(&str, &str)> = text
        .lines()
        .filter(|line| !line.is_empty() && !line.starts_with('#'))
        .map(|line| {
            line.split_once('\t')
                .unwrap_or_else(|| panic!("no tab in row {line:?}"))
        })
        .collect();
    // `lookup_word`'s tests, like upstream's lookup, rely on the order.
    assert!(
        rows.windows(2).all(|pair| pair[0].0 < pair[1].0),
        "{} is not sorted, or holds a duplicate",
        data.display()
    );

    let mut out = format!(
        "// @generated by build.rs from {DATA}.\n\n\
         use super::token::TokenType as T;\n\n\
         #[rustfmt::skip]\n\
         pub static SQL_KEYWORDS: [(&str, T); {}] = [\n",
        rows.len()
    );
    for (key, byte) in rows {
        // `{key:?}` escapes the quotes and backslashes of the printable ASCII keys.
        assert!(key.is_ascii(), "non-ASCII key {key:?}");
        out.push_str(&format!("    ({key:?}, T::{}),\n", token_type(byte)));
    }
    out.push_str("];\n");

    let dest = Path::new(&env::var_os("OUT_DIR").expect("OUT_DIR")).join("keyword_table.rs");
    fs::write(dest, out).expect("write keyword_table.rs");
}
