#!/usr/bin/env python3
"""Generate/check independent v0.3.3 SQL boolean and fingerprint expectations."""

from __future__ import annotations

import argparse
import hashlib
import os
import signal
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PIN = "f6c336efc0ddac2597fd27d3b1b7db9c87613e8d"
OUTPUT = ROOT / "tests/parity/sqli_oracle.tsv"
TRIM_BYTES = b" \t\n\r"
ORACLE_TIMEOUT_SECONDS = 300


def fixture_input(path: Path) -> bytes:
    contents = path.read_bytes()
    current = None
    section = bytearray()
    sections: dict[bytes, bytes] = {}
    expected_markers = [b"--TEST--", b"--INPUT--", b"--EXPECTED--"]
    marker_index = 0
    lines = contents.split(b"\n")
    if lines and lines[-1] == b"":
        lines.pop()
    for line in lines:
        if marker_index < len(expected_markers) and line.strip() == expected_markers[marker_index]:
            if current is not None:
                sections[current] = bytes(section).rstrip(TRIM_BYTES)
            current = expected_markers[marker_index]
            section = bytearray()
            marker_index += 1
        else:
            if current is None:
                raise ValueError(f"{path.name}: text before --TEST--")
            section.extend(line)
            section.append(0x0A)
    if current is not None:
        sections[current] = bytes(section).rstrip(TRIM_BYTES)
    if marker_index != 3 or b"--INPUT--" not in sections:
        raise ValueError(f"{path.name}: incomplete Go corpus sections")
    return sections[b"--INPUT--"]


def run_oracle(command: list[str], request: bytes, environment: dict[str, str]) -> bytes:
    """Run the Go oracle with a deadline and terminate its process group on timeout."""
    process = subprocess.Popen(
        command,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=environment,
        start_new_session=True,
    )
    try:
        stdout, stderr = process.communicate(input=request, timeout=ORACLE_TIMEOUT_SECONDS)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(process.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass
        stdout, stderr = process.communicate()
        diagnostic = stderr.decode("utf-8", "replace").strip()
        suffix = f"; stderr: {diagnostic}" if diagnostic else ""
        raise RuntimeError(f"Go oracle exceeded its {ORACLE_TIMEOUT_SECONDS}s deadline{suffix}") from None
    if process.returncode != 0:
        raise subprocess.CalledProcessError(process.returncode, command, output=stdout, stderr=stderr)
    return stdout


def oracle_rows(source: str | None) -> list[str]:
    fixtures = sorted((ROOT / "tests/corpus").glob("test-sqli-*.txt"))
    requests = bytearray()
    hashes: dict[str, str] = {}
    for fixture in fixtures:
        raw = fixture_input(fixture)
        name = fixture.name
        hashes[name] = hashlib.sha256(raw).hexdigest()
        requests.extend(name.encode("ascii"))
        requests.extend(b"\t")
        requests.extend(raw.hex().encode("ascii"))
        requests.extend(b"\n")

    command = [str(ROOT / "tools/parity/go-oracle")]
    if source:
        command.append(source)
    environment = os.environ.copy()
    if source:
        environment["LIBINJECTION_GO_SOURCE"] = source
    oracle_stdout = run_oracle(command, bytes(requests), environment)
    lines = oracle_stdout.decode("ascii").splitlines()
    if len(lines) != len(fixtures):
        raise RuntimeError(f"Go oracle returned {len(lines)} records for {len(fixtures)} SQL fixtures")

    rows = [f"# Oracle: libinjection-go {PIN}; generated by tools/parity/record_sqli_oracle.py"]
    rows.append("# fixture\tinput_sha256\tdetected\tfingerprint_hex")
    for fixture, line in zip(fixtures, lines, strict=True):
        fields = line.split("\t")
        if len(fields) != 22 or fields[0] != fixture.name:
            raise RuntimeError(f"malformed Go oracle row for {fixture.name}")
        error = bytes.fromhex(fields[1])
        if error:
            raise RuntimeError(f"Go oracle error for {fixture.name}: {error.decode('utf-8', 'replace')}")
        if fields[2] not in {"0", "1"}:
            raise RuntimeError(f"invalid Go SQL boolean for {fixture.name}: {fields[2]!r}")
        try:
            fingerprint_hex, encoded_length = fields[3].rsplit(":", maxsplit=1)
            fingerprint_bytes = bytes.fromhex(fingerprint_hex)
            fingerprint_length = int(encoded_length, 16)
        except (ValueError, IndexError) as error:
            raise RuntimeError(f"invalid Go fingerprint field for {fixture.name}: {fields[3]!r}") from error
        if len(fingerprint_bytes) != fingerprint_length:
            raise RuntimeError(f"Go fingerprint length mismatch for {fixture.name}: {fields[3]!r}")
        if (fields[2] == "0") != (not fingerprint_bytes):
            raise RuntimeError(f"Go SQL boolean/fingerprint contract violation for {fixture.name}")
        rows.append(f"{fixture.name}\t{hashes[fixture.name]}\t{fields[2]}\t{fingerprint_hex}")
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--go-source", help="pinned libinjection-go checkout")
    parser.add_argument("--update", action="store_true", help="write the independent SQL oracle baseline")
    args = parser.parse_args()
    rows = oracle_rows(args.go_source)
    actual = "\n".join(rows) + "\n"
    if args.update:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(actual, encoding="ascii")
        print(f"updated {OUTPUT.relative_to(ROOT)} with {len(rows) - 2} SQL fixture expectations")
        return
    expected = OUTPUT.read_text(encoding="ascii")
    if actual != expected:
        raise SystemExit("SQL boolean/fingerprint oracle baseline changed; review and regenerate explicitly")
    print(f"verified {len(rows) - 2} independent SQL boolean/fingerprint expectations")


if __name__ == "__main__":
    main()
