#!/usr/bin/env python3
"""Regenerate the data tables ported from an upstream libinjection checkout.

    tools/gen_tables.py [path/to/libinjection]

Writes src/sqli/keyword_table.rs (from src/libinjection_sqli_data.h) and
src/xss/events.rs (from src/libinjection_xss.c). Entry order is preserved:
the keyword lookup is the same binary search upstream uses.
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

TOKEN_TYPES = {
    "k": "Keyword",
    "U": "Union",
    "B": "Group",
    "E": "Expression",
    "t": "SqlType",
    "f": "Function",
    "n": "Bareword",
    "1": "Number",
    "v": "Variable",
    "s": "String",
    "o": "Operator",
    "&": "LogicOperator",
    "c": "Comment",
    "A": "Collate",
    "T": "Tsql",
    "F": "Fingerprint",
}


def header(upstream, source):
    rev = subprocess.run(
        ["git", "-C", str(upstream), "describe", "--tags", "--always"],
        capture_output=True,
        text=True,
        check=False,
    ).stdout.strip()
    at = f" at {rev}" if rev else ""
    return (
        f"// @generated by tools/gen_tables.py from libinjection's {source}{at}.\n"
        "// Do not edit by hand.\n\n"
    )


def rust_str(word):
    assert all(32 <= ord(c) < 127 for c in word), word
    return '"' + word.replace("\\", "\\\\").replace('"', '\\"') + '"'


def keyword_table(upstream):
    source = "src/libinjection_sqli_data.h"
    text = (upstream / source).read_text()
    body = re.search(r"sql_keywords\[\] = \{(.*?)\n\};", text, re.S).group(1)
    entries = re.findall(r'\{"((?:[^"\\]|\\.)*)", \'(.)\'\}', body)
    declared = int(re.search(r"sql_keywords_sz = (\d+);", text).group(1))
    assert len(entries) == declared, (len(entries), declared)
    # The lookup upper-cases the key only, so a lower-case entry could never match.
    assert not any(re.search("[a-z]", word) for word, _ in entries)

    out = [header(upstream, source)]
    out.append("use super::token::TokenType as T;\n\n")
    out.append("#[rustfmt::skip]\n")
    out.append(f"pub(super) static SQL_KEYWORDS: [(&str, T); {len(entries)}] = [\n")
    for word, kind in entries:
        out.append(f"    ({rust_str(word)}, T::{TOKEN_TYPES[kind]}),\n")
    out.append("];\n")
    return "".join(out)


def event_table(upstream):
    source = "src/libinjection_xss.c"
    text = (upstream / source).read_text()
    body = re.search(
        r"BLACKATTREVENT\[\] = \{(.*?)\{NULL, TYPE_NONE\}\};", text, re.S
    ).group(1)
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
    entries = re.findall(r'\{\s*"([^"]+)",\s*(\w+)\s*\}', body)
    assert entries and all(kind == "TYPE_BLACK" for _, kind in entries)

    out = [header(upstream, source)]
    out.append("/// Event handler names, without their `on` prefix.\n")
    out.append("#[rustfmt::skip]\n")
    out.append(f"pub(super) static BLACK_ATTR_EVENTS: [&str; {len(entries)}] = [\n")
    for name, _ in entries:
        out.append(f"    {rust_str(name)},\n")
    out.append("];\n")
    return "".join(out)


def main():
    upstream = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "libinjection"
    (ROOT / "src/sqli/keyword_table.rs").write_text(keyword_table(upstream))
    (ROOT / "src/xss/events.rs").write_text(event_table(upstream))


if __name__ == "__main__":
    main()
